### ISSUE TITLE
Replace QueryResultRows with IEnumerable

### ISSUE THREAD

**Issue by miyconst** [StarcounterApps/Simplified#100]
The `master-v2.4` branch contains multiple usage of the deprecated class `QueryResultRows`, it should be replaced with `IEnumerable`.

**Comment by warpech** [comment]
Was it necessary to do these changes only in branch `master-v2.4`? I thought they are compatible with 2.3 as well

**Comment by miyconst** [comment]
As we agreed multiple times, we deprecate old API features in `2.3` and remove them in `2.4`. Removing `QueryResultRow` from `2.3` will break multiple apps.

**Comment by warpech** [comment]
True, that actually changes API of Simplified. I didn't think of that.

Closing as done
