### ISSUE TITLE
Make this repository public

### ISSUE THREAD

**Issue by Mackiovello** [StarcounterApps/Simplified#49]
This repo is used in all the sample apps and is mentioned several times in the documentation. It is unfortunate that we cannot link to this repo since it is integral to much of what we show people that are new to Starcounter.

To make this possible, the use of `DbMapping` has to be removed.

@alemoi

**Comment by Mackiovello** [comment]
The old branches are deleted and the repo is set to public. Thank you @alemoi! Closing.

**Comment by alemoi** [comment]
> The old branches are deleted and the repo is set to public. Thank you @alemoi! Closing.

Awesome @Mackiovello ! Can you please double check after me that there are no traces of database mapping there? Not that I could find!

**Comment by Mackiovello** [comment]
I'm not sure how database mapping actually looks in code. Look around anyway and did some searches on the code and didn't find anything. It seems like you did a thorough job :rocket:
