### ISSUE TITLE
Change fields to properties in all database classes

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Simplified#53]
As requested in https://github.com/Starcounter/TechComm/issues/340, change fields to properties in all `[Database]` classes in this repo.

Notice (see https://github.com/StarcounterApps/Simplified#branches-in-this-repo) that unlike apps repos, work in this repo need to be done in form of a PR to the `master` branch. After it is accepted, merge `master` to `develop`.

While working on this, please check if the schema is compatible when changing from field to property - meaning, no data is lost.

**Comment by Mihaiii** [comment]
Made the changes in Simplified and tested the result in Content app.
I get this error:

> A synonym targeted a non-persistent field. Simplified.Ring3.WebAddress.Url, synonymous to Simplified.Ring1.Something.Name (ScErrSynTargetNotPersistent (SCERR4070))

Undo some changes, try again, I get this error:

> Illegal element for the SynonymousTo attribute. Illegal synonym: Simplified.Ring2.SomebodyGroupMemberSomebody/Group (ScErrIllegalSynonymElement (SCERR4303))

Undo all changes, just to be sure I didn't mess something up and everything is ok.

**Comment by Mihaiii** [comment]
I can't replace the fields that have the `SynonymousTo` attribute.
If I do this, I get [this](https://github.com/Starcounter/level1/wiki/SCERR4070) error.

@warpech Should I replace everything else?

**Comment by warpech** [comment]
Yes please. Future of synonyms is unclear: https://github.com/Starcounter/CompanyTrack/issues/180

**Comment by Mihaiii** [comment]
Closing as done.

**Comment by warpech** [comment]
@Mihaiii what's the reason not everything was replaced? For example: https://github.com/StarcounterApps/Simplified/blob/1615a9b1a3a9ab3baacf125468c636235208c235/Ring3/User/SystemUser.cs#L6-L7

**Comment by Mihaiii** [comment]
Closing as redone.
