### ISSUE TITLE
Build fails on TeamCity

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Simplified#55]
@ubbeK, could you please help us out and check why builds of https://github.com/StarcounterApps/Simplified/commits/master are failing in TeamCity?

**Comment by ubbeK** [comment]
```
[23:11:53]The argument 'C:\TeamCity\BuildAgent\work\ded9bbadb0ffe4b2\simplified\tools\Teamcity.ps1' to the -File parameter does not exist. Provide the path to an existing '.ps1' file as an argument to the -File parameter.
[23:11:53]Process exited with code -196608
```

The `tools\Teamcity.ps1` file does not exist on `Master` branch, only on `Develop`

**Comment by ubbeK** [comment]
The reason for this is that both `Simplified Develop` and `Simplified Master` TeamCity jobs inherits its build configuration from `Simplified_Template` which executes:

1. msbuild simplified/Simplified.sln
2. simplified/tools/Teamcity.ps1 -checkoutdir %teamcity.build.checkoutDir% -nunitversion 3.6.1 -browsersToRun Chrome,Firefox -testedApp Simplified -appsToRun Simplified

I will try if `simplified/tools/Teamcity.ps1` work on master as is.

On a side note, I find the setup of the Simplified.csproj quite confusing. Why is the output path configured to `$(StarcounterBin)\Public Assemblies\`? I don't like output folder outside the repo. If one is developing and want to try it out, then the person should compile be `msbuild Simplified.sln -p:OutputPath=%StarcounterBin%\Public Assemblies\` aswell as the Teamcity jobs.

**Comment by warpech** [comment]
That was made a while ago by @alemoi to allow us for easier changes in Simplified. 

Also, Starcounter does not support loading the same DLL in different versions, so we cannot allow apps to use Simplified as a copy - they all need to load it from the same location for compatibility.

**Comment by chrhol** [comment]
> On a side note, I find the setup of the Simplified.csproj quite confusing. Why is the output path configured to `$(StarcounterBin)\Public Assemblies\`? 

> That was made a while ago by @alemoi to allow us for easier changes in Simplified.

If I'm not mistaken, this should already have been changed in develop branch (compatible with sc2.4/develop) where simplified is no longer included in Starcounter

**Comment by ubbeK** [comment]
Sure, but just make a script that does that for us, and let developers and TeamCity call that one. Because now I have to delete Simplified.dll in Starcounter dir before building the solution.

**Comment by ubbeK** [comment]
> If I'm not mistaken, this should already have been changed in develop branch (compatible with sc2.4/develop) where simplified is no longer included in Starcounter

Yes, the develop branch seems to have output path at `bin\Release\`

**Comment by ubbeK** [comment]
Master TC build is now successfully executed, see #57 for the develop build. Closing this issue
