### ISSUE TITLE
Develop TeamCity build fails

### ISSUE THREAD

**Issue by ubbeK** [StarcounterApps/Simplified#57]
`Simplified.csproj error ScErr1234: This project specifies its compatible with Starcounter 2.4 while the installed version of Starcounter requires 2.3. The probable cause is you have an incompatible version of the Starcounter Visual Studio extension installed. For Starcounter version 2.3, we recommend extension versions >=1.0.0 <2.0.0. Please see https://github.com/Starcounter/Starcounter.VisualStudio/wiki/Version-compatibility if you need further help.`

**Comment by ubbeK** [comment]
@warpech Is master-branch for Starcounter 2.3 Teamcity builds (RC) and develop-branch for Starcounter 2.4 Teamcity builds (Develop)?

**Comment by ubbeK** [comment]
Because when develop-branch is built against Starcounter 2.4 it passes, but master-branch is built agains 2.2 Released at the moment

**Comment by ubbeK** [comment]
TC builds are now passing.

`develop` branch: 

- Build against `Windows Develop Nightly`
- triggered: on `develop` branch commit + Successful `Windows Develop Nightly`



`master` branch: 
- Build against `Windows RC Nightly`
- triggered: on `master` branch commit + Successful `Windows RC Nightly`


closing issue

**Comment by warpech** [comment]
> @warpech Is master-branch for Starcounter 2.3 Teamcity builds (RC) and develop-branch for Starcounter 2.4 Teamcity builds (Develop)?

Yes, as explained in https://github.com/StarcounterApps/Simplified#branches-in-this-repo

**Comment by warpech** [comment]
Thanks, you're our hero of today!
