### ISSUE TITLE
Everyone gets confused by branches in this repo

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Simplified#63]
**Everyone** gets confused by specific branching scheme used in this repo. 

Quotation from README.md:

> Starcounter 2.2 and 2.3 comes with DLL built from Simplified master branch.
>
> Starcounter 2.4 comes with DLL built from Simplified develop branch. This branch is not compatible with Starcounter 2.2 and 2.3.

----

Maybe it would be easier if we did differently?

- `develop` branch works with 2.2, 2.3 and is NOT used by Starcounter build
- `master` branch works with 2.2, 2.3 and is used by a Starcounter build
- `master-v2.4` branch works with 2.4 and is used by a Starcounter build

That branching scheme would let us work like normal people - target feature branches towards `develop`.

@ubbeK, @un-tone, @PatrykSzwer, @bouguila, @Mihaiii WDYT?

**Comment by ubbeK** [comment]
I am fine with this solution.

**Comment by PatrykSzwer** [comment]
I agree since I've became victim of this solution as well. It will definitely improve readability.

**Comment by bouguila** [comment]
it seems to be a convenient solution.

**Comment by un-tone** [comment]
Who will merge `develop` branch to `master`, and when?

**Comment by warpech** [comment]
Merge from `develop` to `master` should be made often, so that the `develop` branch in our prefab apps works with the current Starcounter RC.

**Comment by un-tone** [comment]
OK. I agree with the solution

**Comment by warpech** [comment]
Seems that we have a consensus! @ubbeK could you please proceed with it?

**Comment by ubbeK** [comment]
Sure. First thing tomorrow.

I will fix the following, please stop me if I misunderstood.

1. rename `develop` branch to `master-v2.4`

2. update TeamCity trigger Starcounter RC (2.3.1):
`+ any`
`- master-v2.4*` 
`- v2.4*`

3. update TeamCity trigger Starcounter Develop (2.4):
`+ master-v2.4*` 
`+ v2.4*` if a branch is named v.2.4*, then TeamCity will execute it towards Starcounter Develop verssion

4. Update README.md

**Comment by ubbeK** [comment]
this issue has been implemented.

Current roles for branches:

- `master`  - released with Starcounter versions 2.2 and 2.3
- `master-v2.4` - released with Starcounter version 2.4
- `develop` - development branch for `master` branch i.e. Starcounter versions 2.2 and 2.3

**Comment by warpech** [comment]
Great job, thanks!
