### ISSUE TITLE
StarcounterVersionCompatibility is not in develop

### ISSUE THREAD

**Issue by alemoi** [StarcounterApps/Simplified#65]
The develop Starcounter builds are failing because `StarcounterVersionCompatibility` is not set in Simplified.csproj in `develop`

Did someone forgot to merge or there is another reason? CC @warpech @un-tone

**Comment by un-tone** [comment]
I suppose it is related to https://github.com/StarcounterApps/Simplified/issues/63 and I guess @ubbeK can help

**Comment by ubbeK** [comment]
`develop`-branch is now development branch for `master` i.e. Starcounter 2.2 and 2.3

`master-v2.4`-branch is for Starcounter 2.4

So I think that I forgot to update TC jobs for Development jobs from `develop` branch to `master-v2.4`

**Comment by ubbeK** [comment]
It should be fixed now, will close issue after TC jobs are finished.

Thanks for reporting

**Comment by ubbeK** [comment]
TC Starcounter Develop Jobs has been updated to target `Simplified master-v2.4` branch.

Closing
