### ISSUE TITLE
Purpose of Develop branch

### ISSUE THREAD

**Issue by Joltrix** [StarcounterApps/Simplified#68]
How should the contributing to this repo work? 

After reading this [PR](https://github.com/StarcounterApps/Simplified/pull/66#issuecomment-321765564) and StarcounterApps/Simplified#63 I "came to the conclusion" that a contribution should work like this:

1. Make changes in separate branch
2. Make a PR with those changes into `develop` branch
3. Update `master` branch from `develop` branch

is this correct?

Cause at the moment, I made a [PR](https://github.com/StarcounterApps/Simplified/pull/67) into `develop`, which I then merged.

But now, when I try to update `master` branch, it wants to include the changes to `develop`'s `.csproj` file, (which is for Starcounter version 2.4) and won't build. (it is also failing the teamcity tests)

Am I missing something? or doing something wrong?
Or should I just update the `master` branch from the `develop` branch and exclude the changes to the `.csproj` file?

cc @warpech @un-tone @PatrykSzwer @bouguila @ubbeK

**Comment by un-tone** [comment]
I assume you made this commit 83d629873c9a89c25c89b1b1144256bf61346bc1 by mistake. There you merged `develop` branch with this commit 1b44a588f699b5e57a6b573fd6bb8c2de9e20f0a which is quite old and used in SC 2.4.
In that commit you can't see this change for some unknown for me reason.
```xml
<StarcounterVersionCompatibility>2.4</StarcounterVersionCompatibility>
```
Maybe there are some anomaly in Git.

**Comment by un-tone** [comment]
I reverted that incorrect changes. In future please always use PRs way even when merging `develop` into `master`.

**Comment by Joltrix** [comment]
Yeah, I'm using github desktop, and for the Simplified repo it's been malfunctioning for the past week or so... Thank you for fixing this issue :)

Also, since we're at it, one question. If I want to make a change, where should I make a PR to? To develop, and then make a PR to master?

**Comment by un-tone** [comment]
Yes, you should make PRs with your changes into `develop`.
After that you can make a PR from `develop` to `master` if you want your changes to be used in a next SC build. This PR does not even require approvals, I suppose. This approach just makes such mergings more visual and eliminates issues like was above.

**Comment by Joltrix** [comment]
Okay! Thank you for clarifying :)
