### ISSUE TITLE
Obsolete `Key`

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Simplified#85]
It seems to me that the property `Key` in Simplified.Ring1.Something should be obsoleted for the reasons explained in https://github.com/Starcounter/Home/issues/252.

In the Website app we already stopped using it: https://github.com/StarcounterApps/Website/issues/216

cc @StarcounterApps/starcounter

**Comment by Mackiovello** [comment]
Is it possible to do Typed JSON data-bindings do the id without having `Key` as a property on the class? 

I thought `Key` was a way to enable data-bindings.

**Comment by warpech** [comment]
> I thought `Key` was a way to enable data-bindings.

Yes, and that works well but `Key` also started to get used in SQL queries and that is not good. So my proposal is to remove `Key` from Something and add it as a getter in the view-models.

Any better idea?

**Comment by Mackiovello** [comment]
No, it's the best way to prevent that behavior. But I don't see why you would ever query for `Key`; to check for equality there's the `=` operator in SQL and to retrieve a single object there's `Db.FromId`. 

It's your call whether the cost of changing Simplified and the apps that use it vs. trying to teach people how to use the `Key` property. I believe in preventing behavior that could cause bugs, so removing the property should be fine.

**Comment by warpech** [comment]
https://github.com/StarcounterApps/Website/issues/216 (left side of code comparison) shows what are the legitimate ways `Key` could be used in queries, if it worked correctly.

**Comment by miyconst** [comment]
+1, it should be obsolete in `2.3.1` and removed in `2.4`.

**Comment by miyconst** [comment]
@LarsTjernstrom please take care of this issue.

**Comment by Mihaiii** [comment]
Maybe I'm too tired at this moment, but I'm asking anyway.
How should I handle cases like [this one](https://github.com/StarcounterApps/Calendar/blob/develop/src/Calendar/ViewModels/EventsPage.json.cs#L82) ? `Key` is used [here](https://github.com/StarcounterApps/Calendar/blob/develop/src/Calendar/wwwroot/Calendar/viewmodels/EventsPage.html#L30).

**Comment by Mihaiii** [comment]
All the apps under apps-team are covered.

**Comment by Mackiovello** [comment]
It seems like this is done then. Well done @Mihaiii! Closing
