### ISSUE TITLE
Outdated text and diagram about branches in README.md

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Simplified#93]
`README.md` text and the SVG diagram mentions `develop` branch which no longer exists.

@Mihaiii can you pls update it?

The source code for the diagram is included as metadata in the SVG file. To edit it, simply load the SVG file in https://www.draw.io/

**Comment by Mihaiii** [comment]
This issue was discussed here: https://github.com/Starcounter/RebelsLounge/issues/175#issuecomment-347589973 .

TLDR: `develop` branch is now restored.
